spring:
  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers:
            - "centos00"
          zkNodes:
            - "centos00"
management:
  security:
    enabled: false