server:
  port: 8781
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: boot-admin-server
management.security.enabled: false