server:
  port: 8767
spring:
  application:
    name: config-server-1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/catcher92/springbootdemo
          search-paths: src/main/resources
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka